### ISSUE TITLE
'bite create' can inizialize a variable with the bug number

### ISSUE THREAD

**Issue by asarubbo** [radhermit/bugbite#35]
When you file a bug, is very likely that you need the bug number to make further operations (attach logs, do more comments, cc people and so on).

So would be very useful that given a variable (like BUGBITE_CREATED_BUG), `bite` unsets it before file the bug and then fills it with the bug number if the creation succeded.

That should work only for creation, at least for bugzilla service.

**Comment by radhermit** [comment]
I'm still unclear on how this would work since bite would be running in a child process and unable to alter the parent process environment of the shell. To make it work as expected in the shell requires writing shell specific plugins so bite would be running in the same process at which point I'd rather just write bindings for more usable programming languages :smile:.

I will also note that currently bite uses stderr for output when stdout is connected to a terminal and uses stdout when it's not, e.g. piping or capturing output in a subshell. Therefore something like `BUG_ID=$(bite create ...)` would be empty when there is an error and non-empty with the ID when successful thus one could get by with only checking for BUG_ID existence and not be forced to check the return code.

Overall, I think this kind of thing is better left to more advanced programming languages if I ever get around to working on bindings.

**Comment by radhermit** [comment]
Closing this since it should be possible as mentioned above via `BUG_ID=$(bite create ...)` with checks if the resulting variable is empty or not. One might even get away with not explicitly checking since if $BUG_ID was used for future `bite` calls they should fail as ones that modify bugs require an ID argument.
